upgrade for 0.11
alexmingoia/purescript-pux pull request #116
Opened 2017-04-19 18:21 UTC by justinwoo

depends on https://github.com/slamdata/purescript-css/pull/60

2017-04-19 21:40 UTC, justinwoo commented
updated node target version to 6 since 5 doesn't run the install script and the new LTS is 6 anyhow.

2017-04-29 12:39 UTC, sloosch commented on src/Pux.purs
> +        case ev of
````later```` was replaced with ````delay```` (https://github.com/slamdata/purescript-aff/commit/1ed0d751dd7427074f98d86220566a58572d5aa7)
```delay (Milliseconds 0.0)``` should then be placed above the case

2017-04-29 12:44 UTC, sloosch commented on src/Pux.purs
> +  _ <- runSignal $ effectsSignal ~> sequence_
you don`t need to discard `Unit` explicitly

2017-04-29 12:50 UTC, sloosch requested changes

2017-04-29 12:50 UTC, sloosch commented on src/Pux/Router.purs
> +    _ <- guard $ A.length param' == 2
you don't need to discard ``Unit`` explicitly. import Prelude.discard

2017-04-29 12:50 UTC, sloosch commented on src/Pux.purs
> -        later $ case ev of
````later```` was replaced with ````delay```` (https://github.com/slamdata/purescript-aff/commit/1ed0d751dd7427074f98d86220566a58572d5aa7)
```delay (Milliseconds 0.0)``` should therefore be placed above the `case`

2017-04-29 12:50 UTC, sloosch commented on src/Pux.purs
> +  _ <- runSignal $ effectsSignal ~> sequence_
you don't need to discard ``Unit`` explicitly. import Prelude.discard

2017-05-01 21:11 UTC, justinwoo commented on src/Pux.purs
> -        later $ case ev of
seems like a smell, but yeah, updated

2017-05-01 21:11 UTC, justinwoo commented
updated with @sloosch's suggestions

2017-05-02 05:43 UTC, closed without merging